#!/usr/bin/env bash
# This script displays a list of currently running processes

# Use ps command to display all processes, for all users, including those without a TTY, in a user-oriented format, showing process hierarchy
ps axjf
