#!/bin/sh
### BEGIN INIT INFO
# Provides:          101-manage_my_process
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: manage_my_process init script
# Description:       Manages manage_my_process process
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="manage_my_process init script"
NAME=manage_my_process
PIDFILE=/var/run/my_process.pid
SCRIPT_PATH=/path/to/manage_my_process

case "$1" in
  start)
    echo "Starting $DESC: $NAME"
    $SCRIPT_PATH start
    ;;
  stop)
    echo "Stopping $DESC: $NAME"
    $SCRIPT_PATH stop
    ;;
  restart)
    echo "Restarting $DESC: $NAME"
    $SCRIPT_PATH restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
    ;;
esac

exit 0
