#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
    # If the process is running, kill it
    kill "$pid"
    echo "Process 4-to_infinity_and_beyond stopped."
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
