#!/usr/bin/env bash
# This script displays information about each user in /etc/passwd using a while loop and IFS

# Read /etc/passwd line by line using a while loop
while IFS=: read -r username _ uid gid gecos home shell; do
    # Extract additional information
    IFS=',' read -r _ _ _ password _ <<< "$gecos"
    IFS=':' read -r _ _ _ _ info <<< "$gecos"

    # Display user information
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
