#!/usr/bin/env bash
# This script extracts the visitor IP along with the HTTP status code from the Apache log file using awk

# Use awk to extract IP address and HTTP status code from the Apache log file
awk '{print $1, $9}' apache-access.log
